[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.20.0,<2.0.0",
    "numba",
    "numba-scipy",
    "scipy",
    "cmake",
    "anywidget>=0.9.9",
    "ipywidgets>=8.0.0",
    "requests"
]
build-backend = "setuptools.build_meta"
