name: Unit Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libopenmpi-dev libgl1-mesa-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy matplotlib
    - name: Install PyMFEM
      run: |
        git clone https://github.com/melekderman/PyMFEM.git /tmp/mfem
        cd /tmp/mfem
        python setup.py install
    - name: Install PyGLVis
      run: |
        git clone https://github.com/melekderman/pyglvis.git /tmp/pyglvis
        cd /tmp/pyglvis
        pip install .
    - name: Run unit tests
      run: |
        pytest tests/unit/